import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#0f172a',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
    },
    secondCon: {
        backgroundColor: '#1e293b',
        borderWidth: 2,
        borderColor: '#00ffe5',
        padding: 60,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#00ffe5',
        shadowOffset: {width: 0, height: 0},
        shadowOpacity: 0.6,
        shadowRadius: 20,
        elevation: 10,
    },
    title: {
        fontSize: 20,
        color: '#38bdf8',
        marginTop: 25,
        fontWeight: '600',
        textShadowColor: '#0ea5e9',
        textShadowOffset: {width: 0, height: 1},
        textShadowRadius: 10,
        textAlign: 'center',
    },
    microAnimationContainer: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    micro: {
        width: 90,
        height: 90,
        tintColor: '#00ffe5',
    },
    thirdCon: {
        width: '100%',
        maxWidth: 380,
        height: 220,
        backgroundColor: '#1e293b',
        borderRadius: 20,
        marginBottom: 20,
        padding: 20,
        shadowColor: '#38bdf8',
        shadowOffset: {width: 0, height: 4},
        shadowOpacity: 0.5,
        shadowRadius: 12,
        elevation: 10,
    },
    responseScrollView: {
        flex: 1,
        width: '100%',
    },
    responseScrollViewContent: {
        flexGrow: 1,
        justifyContent: 'center',
    },
    resp: {
        color: '#e2e8f0',
        fontSize: 18,
        textAlign: 'center',
        lineHeight: 28,
    },
    selectVoiceButton: {
        marginTop: 25,
        paddingVertical: 14,
        paddingHorizontal: 24,
        backgroundColor: '#0ea5e9',
        borderRadius: 12,
        shadowColor: '#0ea5e9',
        shadowOffset: {width: 0, height: 0},
        shadowOpacity: 0.6,
        shadowRadius: 8,
    },
    selectVoiceButtonText: {
        color: 'white',
        fontSize: 18,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    clearChatButton: {
        marginTop: 15,
        paddingVertical: 12,
        paddingHorizontal: 20,
        backgroundColor: '#ef4444',
        borderRadius: 12,
        shadowColor: '#f87171',
        shadowOffset: {width: 0, height: 0},
        shadowOpacity: 0.5,
        shadowRadius: 6,
    },
    clearChatButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    modalOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(15, 23, 42, 0.95)',
    },
    modalContent: {
        backgroundColor: '#1e293b',
        borderRadius: 20,
        padding: 24,
        width: '90%',
        maxHeight: '80%',
        shadowColor: '#0ea5e9',
        shadowOffset: {width: 0, height: 8},
        shadowOpacity: 0.6,
        shadowRadius: 10,
        elevation: 15,
    },
    modalTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#f8fafc',
        marginBottom: 20,
        textAlign: 'center',
    },
    voiceList: {
        maxHeight: 300,
        marginBottom: 10,
    },
    voiceItem: {
        padding: 16,
        marginBottom: 10,
        borderRadius: 10,
        backgroundColor: '#334155',
        borderColor: '#64748b',
        borderWidth: 1,
    },
    selectedVoiceItem: {
        borderColor: '#00ffe5',
        borderWidth: 2,
        backgroundColor: '#475569',
    },
    voiceText: {
        color: '#f1f5f9',
        fontSize: 16,
    },
    noVoicesText: {
        color: '#94a3b8',
        fontSize: 16,
        textAlign: 'center',
        marginTop: 20,
    },
    closeModalButton: {
        marginTop: 20,
        paddingVertical: 14,
        backgroundColor: '#ef4444',
        borderRadius: 10,
        alignItems: 'center',
    },
    closeModalButtonText: {
        color: '#f8fafc',
        fontSize: 18,
        fontWeight: 'bold',
    },
    stopCon: {
        marginTop: 20,
        paddingVertical: 10,
        paddingHorizontal: 50,
        backgroundColor: '#ef4444',
        borderRadius: 10,
        alignItems: 'center',

    },
    stop: {
        color: "#fff",
        fontSize: 18,
    }
});